// Version information for EnergyHub
// This file is auto-generated by the versioning script
// DO NOT EDIT MANUALLY - Always syncs with package.json version
export const APP_VERSION = "1.1.3";
export const BUILD_DATE = "2026-04-11";
export const BUILD_TIME = "00:35:48";
export const GIT_COMMIT = "unknown";
export const GIT_BRANCH = "unknown";

// Version metadata
export const versionInfo = {
  version: APP_VERSION,
  buildDate: BUILD_DATE,
  buildTime: BUILD_TIME,
  gitCommit: GIT_COMMIT,
  gitBranch: GIT_BRANCH,
  fullVersion: `${APP_VERSION} (${BUILD_DATE} ${BUILD_TIME})`,
};

export default versionInfo;
